Repository Privado-Inc/privado-cli, pull requests merged in 2022-09, with the labels that each got.

#26 hotfix: change scope for err for func OpenURLInBrowser
  pkg/docker/docker.go
Labels: bug

#27 Feat: Support to detect & generate UserIds for CI Environments
  main.go
  pkg/auth/auth.go
  pkg/ci/ci.go
  pkg/ci/providers.json
  pkg/config/app_config.go
Labels: enhancement

#28 Feat: add support for upload flags, fixes privado/#63
  cmd/scan.go
Labels: enhancement

#29 Feature: Add env, bool metric for CI
  cmd/root.go
  cmd/scan.go
  cmd/upload.go
  pkg/telemetry/telemetry.go
Labels: enhancement

#30 Release v2.1.0: Sync dev
  README.md
  cmd/root.go
  cmd/scan.go
  cmd/upload.go
  main.go
  pkg/auth/auth.go
  pkg/ci/ci.go
  pkg/ci/providers.json
  pkg/config/app_config.go
  pkg/docker/docker.go
  pkg/docker/options.go
  pkg/telemetry/telemetry.go
Labels: enhancement, minor
